/* Portfolio data — every node in the network. */

const COLORS = {
  red: "#e5432e",
  yellow: "#ffc928",
  blue: "#3d7bf4",
  green: "#35b558",
  orange: "#f78c1e",
  azure: "#2fb8c9",
  bone: "#e8e6df",
};

/* Skill hubs — the "plates" experiences snap onto. */
const SKILLS = [
  { id: "s-web",      label: "Full-Stack Dev",   color: COLORS.blue },
  { id: "s-data",     label: "Data & AI",        color: COLORS.yellow },
  { id: "s-embedded", label: "Embedded Systems", color: COLORS.orange },
  { id: "s-biz",      label: "Entrepreneurship", color: COLORS.red },
  { id: "s-ops",      label: "Ops & Finance",    color: COLORS.azure },
  { id: "s-lead",     label: "Leadership",       color: COLORS.green },
];

/* Experience bricks. `skills` = which hubs each brick connects to.
   `size` = brick width in studs (2–4), roughly by weight on the CV. */
const EXPERIENCES = [
  {
    id: "handshake",
    title: "Large Language Model Trainer",
    org: "Handshake AI Fellowship",
    dates: "May 2026 – Present",
    place: "Chestnut Hill, MA",
    category: "Work",
    color: COLORS.yellow,
    size: 3,
    skills: ["s-data"],
    points: [
      "Develop challenging multimodal evaluation tasks with verified ground-truth answers to benchmark vision-language models on visual and compositional reasoning.",
    ],
  },
  {
    id: "receivos",
    title: "Software Developer Intern",
    org: "Receivos",
    dates: "Mar 2026 – Jun 2026",
    place: "Chestnut Hill, MA",
    category: "Work",
    color: COLORS.blue,
    size: 4,
    skills: ["s-web", "s-data"],
    points: [
      "Built a responsive React web UI automating expense tracking and digital business-card management, minimizing manual data entry for traveling professionals.",
      "Architected backend logic and cloud-infrastructure automation to streamline environment provisioning and CI/CD, keeping intelligent receipt-capture tools highly available.",
      "Optimized AI-driven document intelligence by monitoring OCR and data-reasoning modules to ensure 100% accuracy in automated expense categorization.",
    ],
  },
  {
    id: "daq",
    title: "Embedded DAQ Firmware",
    org: "Mecha Eagles Baja Car",
    dates: "Mar 2026 – Present",
    place: "Chestnut Hill, MA",
    category: "Project",
    color: COLORS.orange,
    size: 3,
    skills: ["s-embedded", "s-data"],
    points: [
      "Spearheaded the team's first Data Acquisition firmware in C/C++, with real-time sensor polling for engine RPM, vehicle speed, and thermal monitoring.",
      "Implemented non-blocking timing loops for multi-threaded sensor reads across I2C and SPI, preventing data-logging delays with sub-millisecond precision.",
      "Engineered a standardized CSV schema for concurrent SD-card logging and live serial streaming — a single source of truth for vehicle telemetry.",
    ],
  },
  {
    id: "voxwood",
    title: "Founder & Developer",
    org: "Voxwood Indonesia",
    dates: "Mar 2023 – Present",
    place: "Jakarta, IDN",
    category: "Venture",
    color: COLORS.red,
    size: 4,
    skills: ["s-biz", "s-ops", "s-data"],
    points: [
      "Designed a custom inventory system on Google Sheets + Python, automating stock updates for 70+ products and cutting 10+ hours of manual entry per month.",
      "Engineered a Looker Studio financial dashboard aggregating multi-currency sales across 5 global markets, optimizing cash flow for international hotel restorations.",
      "Built a Pandas demand-forecasting model from historical orders — 15% less overstock, contributing to $14K net profit.",
    ],
  },
  {
    id: "bricknation",
    title: "Co-Founder",
    org: "BrickNation Indonesia",
    dates: "Jul 2020 – Present",
    place: "Jakarta, IDN",
    category: "Venture · the origin brick",
    color: COLORS.red,
    size: 4,
    skills: ["s-biz", "s-ops"],
    points: [
      "Run a top-rated Tokopedia LEGO store — 80+ products sold and $7.8K+ in profit. (Yes, this whole site is a tribute.)",
      "96% customer satisfaction across 350+ five-star reviews, holding a 4.9 average rating.",
      "Built the habits of a real business: structured bookkeeping and LEGO market-price analysis for sustainable operations.",
    ],
  },
  {
    id: "tutoring",
    title: "Founder · Debate & Model UN Tutor",
    org: "Private WSC & MUN Tutoring Service",
    dates: "Sep 2023 – Mar 2025",
    place: "Jakarta, IDN",
    category: "Venture",
    color: COLORS.red,
    size: 2,
    skills: ["s-biz", "s-lead"],
    points: [
      "Trained 3 beginner World Scholar's Cup teams weekly — 7 trophies and 40 medals at Global and Tournament-of-Champions levels.",
      "Earned $3K in revenue while learning to run multiple businesses at once.",
      "Mentored 20 beginner students to Best Delegate awards at MUNs within a month.",
    ],
  },
  {
    id: "bostonracing",
    title: "Head of Software Development / IT",
    org: "Boston Racing CRS",
    dates: "Feb 2026 – Present",
    place: "Boston, MA",
    category: "Leadership",
    color: COLORS.blue,
    size: 4,
    skills: ["s-web", "s-ops", "s-lead"],
    points: [
      "Spearheaded a centralized Digital Operating System in Next.js + PostgreSQL unifying inventory, attendance, and bookkeeping for a 50+ member racing team.",
      "Engineered an inventory engine with Prisma ORM — row-level locking and atomic transactions for 100% data integrity on $10,000+ of racing components.",
      "Integrated webhooks and edge functions for real-time cache revalidation, eliminating expensive database polling.",
      "Pivoted to a QR-code mobile interface, lifting data-entry compliance from 30% to nearly 100%.",
    ],
  },
  {
    id: "fsae",
    title: "Full Stack Developer",
    org: "BC Mecha Eagles (Formula SAE)",
    dates: "Jan 2026 – Present",
    place: "Chestnut Hill, MA",
    category: "Leadership",
    color: COLORS.blue,
    size: 3,
    skills: ["s-web", "s-embedded", "s-lead"],
    points: [
      "Architected and deployed the team's official platform in React + Tailwind — a high-conversion landing page for corporate sponsorships and donor relations.",
      "Implemented GitHub Actions CI/CD so sponsor tiers and milestones go live within minutes of a commit.",
      "Leading the Baja drivetrain technical roadmap: System Requirements Specification and a Python data-logging framework for real-time telemetry.",
    ],
  },
  {
    id: "canimundo",
    title: "Co-Founder · Lead Financial Software Developer",
    org: "CaniMUNDO (Canisius Model UN)",
    dates: "May 2023 – Mar 2025",
    place: "Jakarta, IDN",
    category: "Leadership",
    color: COLORS.azure,
    size: 3,
    skills: ["s-data", "s-ops", "s-lead"],
    points: [
      "Developed a proprietary financial tracking system in Python + Google Sheets API automating budget proposals for 15+ annual international conferences.",
      "Architected a CLI \"data-to-document\" pipeline automating cost-benefit analysis of fixed vs. variable expenses, 100% aligned with school funding policy.",
      "Cut proposal turnaround by 99% — from 3 days to 5 minutes — securing $2,500+ in annual fees.",
    ],
  },
  {
    id: "cef",
    title: "VP & Varsity Debate Team Captain",
    org: "CEF (Canisius English Forum)",
    dates: "May 2023 – Jul 2025",
    place: "Jakarta, IDN",
    category: "Leadership",
    color: COLORS.green,
    size: 3,
    skills: ["s-lead"],
    points: [
      "Directed varsity training and strategy — 15+ first-place finishes at international tournaments including Yale and Yonsei.",
      "Captured multiple Best Speaker awards through complex case building and persuasive advocacy.",
      "Partnered with rival varsity clubs to expand the regional debate circuit.",
    ],
  },
  {
    id: "arscc",
    title: "Co-Founder & Head Secretary",
    org: "Ars : CC (Arsitek CC)",
    dates: "Apr 2024 – Feb 2025",
    place: "Jakarta, IDN",
    category: "Leadership",
    color: COLORS.green,
    size: 2,
    skills: ["s-lead", "s-biz"],
    points: [
      "Co-founded Jakarta's first student-led architecture community for aspiring architects.",
      "Spearheaded 20+ gatherings and workshops for a 70-member organization, featuring industry leaders including architect Andra Matin.",
      "Cultivated a strategic partnership with Ikatan Arsitek Indonesia (IAI) for national recognition and professional mentorship.",
    ],
  },
  {
    id: "canvas",
    title: "Outreach Team",
    org: "CANVAS (Canisius Vanguard SDGs)",
    dates: "Jul 2023 – May 2024",
    place: "Jakarta, IDN",
    category: "Community",
    color: COLORS.green,
    size: 2,
    skills: ["s-lead"],
    points: [
      "Mobilized $10K in donations to fund mangrove reforestation for displaced coastal villages on the Jakarta–Bekasi border.",
      "Executed a 5,000-tree planting initiative against coastal abrasion — 50% of target within the first quarter.",
      "Promoted three large-scale SDG collaboration events with diverse environmental organizations.",
    ],
  },
  {
    id: "wsc",
    title: "Global Student Ambassador",
    org: "World Scholar's Cup",
    dates: "Aug 2020 – Dec 2023",
    place: "International",
    category: "Community",
    color: COLORS.green,
    size: 2,
    skills: ["s-lead"],
    points: [
      "Selected to promote the WSC curriculum across regional schools, growing participation and engagement.",
      "35+ victories across Australia, the United States, Malaysia, and Japan.",
    ],
  },
  {
    id: "ffp",
    title: "Indonesian Student Member",
    org: "Freshman Formation Program",
    dates: "Sep 2026 – Present",
    place: "Chestnut Hill, MA",
    category: "Community",
    color: COLORS.green,
    size: 2,
    skills: ["s-lead"],
    points: [
      "1 of 20 Asian-identifying freshmen chosen to lead community-building initiatives and facilitate social-justice dialogues.",
      "Co-organized the FFP Cafe and FFP Festival charity events — logistics and fundraising outreach for local organizations.",
    ],
  },
  {
    id: "bc",
    title: "B.S. Economics & Computer Science",
    org: "Boston College — Morrissey College of Arts & Sciences",
    dates: "Class of 2029",
    place: "Chestnut Hill, MA",
    category: "Education",
    color: COLORS.bone,
    size: 3,
    skills: ["s-web", "s-data", "s-biz"],
    points: [
      "Coursework: Data Structures & Algorithms, Logic Randomness & Computation, Macro & Micro Theory, Econometric Methods, Linear Algebra.",
      "Languages: Python, JavaScript, TypeScript, Tailwind CSS & HTML, Bash.",
      "Frameworks & tools: React, Git, Vercel, Node.js, PostgreSQL, Looker Studio, Google Sheets API. Akamai Network Engineering certified.",
    ],
  },
];

/* The builder — center of the graph. */
const CENTER = {
  id: "me",
  title: "Patrick Ayrton Hartanto",
  org: "The builder",
  dates: "Jakarta → Boston",
  category: "Tech × Business",
  color: COLORS.yellow,
  size: 5,
  points: [
    "Economics & CS at Boston College. I connect software development to the operational side of business — every brick on this graph taught me one piece of that.",
    "ayrton@bc.edu · linkedin.com/in/patrick-hartanto",
  ],
};
